# Page settings
baseURL = "https://attix-zhang.github.io/resume.github.io/"
languageCode = "en-us"
title = "Attix Zhang resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"


[params]
    author = "Attix Zhang"
    description = "My personal resume."


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Attix Zhang"
        tagline = "Software Engineer"
        avatar = "azhang.jpeg"

    [params.contact]
        enable = true
        location = "Beijing, China"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+86 159 5684 0143"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "attix.zhang.cs@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-weixin"
        #url = "weixin://"
        text = "AttixZhang"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://attixzhangcs.github.io/azhang.github.io"
        text = "azhang.github.io"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Java/Spring/Gradle"
        [[params.skills.list.items]]
        details = "Python/Bash"
        [[params.skills.list.items]]
        details = "Golang"
        [[params.skills.list.items]]
        details = "Docker"
        [[params.skills.list.items]]
        details = "MongoDB/MySQL/Redis"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Scrum Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "Rice University"
        dates = "2017 - 2018"
        [[params.education.list]]
        degree = "BSc Computer Science and Technology"
        university = "East China Normal University"
        dates = "2012 - 2016"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Indeed Invonation Award"
        body = "Gradle migration"
        date = "2019"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2018.7 - 2021.11"
        company = "Indeed Inc."
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Did the Ant to Gradle migration"
        [[params.experience.list.items]]
        details = "Leaded the OSS Gradle migration"
        [[params.experience.list.items]]
        details = "Maintain the Gradle plugins"


    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "My Personal website"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/attix-zhang"
        title = "attix.zhang.cs@gmail.com"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        #[[params.social.list]]
        #icon = "fab fa-twitter-square"
        #url = "//twitter.com/username"
        #title = "@username"

